spring:
  datasource:
    name: user_db
    username: user
    password: user123
    url: jdbc:postgresql://localhost:5432/user_db
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  cache:
    type: redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 3000


eureka:
  instance:
    hostname: ${spring.application.name}
    metadata-map:
      management.context-path: ${server.servlet.context-path}/actuator
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
      enabled: true
  health:
    circuitbreakers:
      enabled: true

#Resilience4j Config
resilience4j:
  circuitbreaker:
    instances:
      course-center:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true


logging:
  file:
    name: ./../data/logs/${spring.application.name}.log

openapi:
  service:
    title: User Center
    version: 1.0.0
    url: ${server.servlet.context-path}
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

cors:
  allowedOrigin: '*'
  allowedMethods: '*'
  allowedHeaders: '*'
  allowedCredentials: 'false'
  corsConfiguration: '/**'