apiVersion: v1
kind: Service
metadata:
  name: notification-center
spec:
  type: LoadBalancer
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: notification-center
    type: backend