apiVersion: v1
kind: Service
metadata:
  name: notification-center
spec:
  type: LoadBalancer
  ports:
    - port: 8085
      targetPort: 8085
  selector:
    app: notification-center
    type: backend