eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: localhost

logging:
  file:
    name: ${spring.application.name}.log