spring:
  application:
    name: SERVICE-REGISTRY

server:
  port: 8761

eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  file:
    name: ${spring.application.name}.log