eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  file:
    name: ./../data/logs/${spring.application.name}.log
  level:
    org:
      springframework: DEBUG

spring:
  cloud:
    compatibility-verifier:
      enabled: false
  zipkin:
    base-url: http://127.0.0.1:9411
  sleuth:
    sampler:
      probability: 1.0