version: '3'
services:
  #MySQL Docker Compose
  course-mysql-db:
    image: mysql
    container_name: course-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: course_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/course-mysql-db
    restart: unless-stopped

  #Postgres Docker Compose
  user-postgresql-db:
    image: postgres
    container_name: user-postgresql-db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user123
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/user-postgresql-db
    restart: unless-stopped

  #MongoDB Docker Compose
  payment-mongodb-db:
    image: mongo
    container_name: payment-mongodb-db
    environment:
      MONGO_INITDB_DATABASE: payment_db
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user123
    ports:
      - "27017:27017"
    volumes:
      - ./data:/var/lib/payment-mongodb-db
    restart: unless-stopped

  #Redis Docker Compose
  redis-cache:
    container_name: redis-cache
    image: redis
    volumes:
      - ./data/redis-cache:/data/redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  #Eureka Server
  discovery-server:
    container_name: discovery-server
    image: registry.hub.docker.com/tharukagayashan/service-registry:latest
    pull_policy: always
    expose:
      - "8761"
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    networks:
      - eureka-network

  #Actuator Admin Server
  actuator-admin:
    container_name: actuator-admin-server
    image: registry.hub.docker.com/tharukagayashan/actuator-admin-server:latest
    pull_policy: always
    expose:
      - "9090"
    ports:
      - "9090:9090"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server
    networks:
      - eureka-network

  #API Gateway
  api-gateway:
    container_name: api-gateway
    image: registry.hub.docker.com/tharukagayashan/api-gateway:latest
    pull_policy: always
    expose:
      - "8765"
    ports:
      - "8765:8765"
    environment:
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=TRACE
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server
    networks:
      - eureka-network

  #User Center
  user-center:
    container_name: user-center
    image: registry.hub.docker.com/tharukagayashan/user-center:latest
    pull_policy: always
    expose:
      - "8084"
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-postgresql-db:5432/user_db?useSSL=false
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user123
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW-DETAILS=ALWAYS
    depends_on:
      - discovery-server
      - api-gateway
    networks:
      - eureka-network

  #Course Center
  course-center:
    container_name: course-center
    image: registry.hub.docker.com/tharukagayashan/course-center:latest
    pull_policy: always
    expose:
      - "8082"
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://course-mysql-db:3306/course-db?user=user
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user123
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW-DETAILS=ALWAYS
    depends_on:
      - discovery-server
      - api-gateway
    networks:
      - eureka-network

  #Payment Center
  payment-center:
    container_name: payment-center
    image: registry.hub.docker.com/tharukagayashan/payment-center:latest
    pull_policy: always
    expose:
      - "8083"
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW-DETAILS=ALWAYS
      - SPRING_DATA_MONGODB_URI=mongodb://user:user123@payment-mongodb-db:27017/payment_db?authSource=admin
      - SPRING_DATA_MONGODB_DATABASE=payment_db
      - SPRING_DATA_MONGODB_USERNAME=user
      - SPRING_DATA_MONGODB_PASSWORD=user123
    depends_on:
      - discovery-server
      - api-gateway
    networks:
      - eureka-network

  #Notification Center
  notification-center:
    container_name: notification-center
    image: registry.hub.docker.com/tharukagayashan/notification-center:latest
    pull_policy: always
    expose:
      - "8085"
    ports:
      - "8085:8085"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW-DETAILS=ALWAYS
    depends_on:
      - discovery-server
      - api-gateway
    networks:
      - eureka-network

  #Prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - user-center
      - course-center
      - payment-center
      - notification-center
    restart: unless-stopped
    networks:
      - eureka-network

  # Grafana
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    links:
      - prometheus:prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
    networks:
      - eureka-network

networks:
  eureka-network:
    driver: bridge
