global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'api-gateway:8765' ]
        labels:
          application: 'API Gateway Application'

  - job_name: 'actuator-admin-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'actuator-admin-server:9090' ]
        labels:
          application: 'Admin Server Application'

  - job_name: 'user-center'
    metrics_path: '/api/v1/user-center/actuator/prometheus'
    static_configs:
      - targets: [ 'user-center:8084' ]
        labels:
          application: 'User Center Application'

  - job_name: 'course-center'
    metrics_path: '/api/v1/course-center/actuator/prometheus'
    static_configs:
      - targets: [ 'course-center:8082' ]
        labels:
          application: 'Course Center Application'

  - job_name: 'payment-center'
    metrics_path: '/api/v1/payment-center/actuator/prometheus'
    static_configs:
      - targets: [ 'payment-center:8083' ]
        labels:
          application: 'Payment Center Application'

  - job_name: 'notification-center'
    metrics_path: '/api/v1/notification-center/actuator/prometheus'
    static_configs:
      - targets: [ 'notification-center:8085' ]
        labels:
          application: 'Notification Center Application'