spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: COURSE-CENTER
            uri: lb://COURSE-CENTER
            predicates:
              - Path=/api/v1/course-center/**
          - id: USER-CENTER
            uri: lb://USER-CENTER
            predicates:
              - Path=/api/v1/user-center/**
          - id: PAYMENT-CENTER
            uri: lb://PAYMENT-CENTER
            predicates:
              - Path=/api/v1/payment-center/**
          - id: NOTIFICATION-CENTER
            uri: lb://NOTIFICATION-CENTER
            predicates:
              - Path=/api/v1/notification-center/**
    compatibility-verifier:
      enabled: false
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
eureka:
  instance:
    preferIpAddress: true
    hostname: ${spring.application.name}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://35.185.34.88:8761/eureka/

logging:
  file:
    name: ./../data/logs/${spring.application.name}.log
  level:
    org.springframework: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
      enabled: true

openapi:
  service:
    title: Swagger Documentation
    version: 1.0.0
    url: http://localhost:8765/v3/api-docs

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /api/v1/course-center/v3/api-docs
        name: Course Service
      - url: /api/v1/user-center/v3/api-docs
        name: User Service
      - url: /api/v1/payment-center/v3/api-docs
        name: Payment Service