spring:
  application:
    name: API-GATEWAY

eureka:
  instance:
    preferIpAddress: true
    hostname: ${spring.application.name}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  file:
    name: ${spring.application.name}.log

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
      enabled: true

server:
  port: 8765