spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: COURSE-CENTER
            uri: lb://COURSE-CENTER
            predicates:
              - Path=/api/v1/course-center/**
          - id: USER-CENTER
            uri: lb://USER-CENTER
            predicates:
              - Path=/api/v1/user-center/**
          - id: PAYMENT-CENTER
            uri: lb://PAYMENT-CENTER
            predicates:
              - Path=/api/v1/payment-center/**
          - id: NOTIFICATION-CENTER
            uri: lb://NOTIFICATION-CENTER
            predicates:
              - Path=/api/v1/notification-center/**

eureka:
  instance:
    preferIpAddress: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS}
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
  client:
    registerWithEureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA}
    fetchRegistry: ${EUREKA_CLIENT_FETCH_REGISTRY}
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}

logging:
  file:
    name: ${spring.application.name}.log

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
      enabled: true