apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
  labels:
    app: service-registry
    type: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      type: backend
      app: service-registry
  template:
    metadata:
      name: service-registry
      labels:
        app: service-registry
        type: backend
    spec:
      containers:
        - name: service-registry
          image: us.gcr.io/gcloud-test-429808/service-registry:latest
          ports:
            - containerPort: 8761