apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-center
  labels:
    app: payment-center
    type: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      type: backend
      app: payment-center
  template:
    metadata:
      name: payment-center
      labels:
        app: payment-center
        type: backend
    spec:
      containers:
        - name: payment-center
          image: us.gcr.io/active-sun-419904/payment-center:v1
          ports:
            - containerPort: 9090