apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-center
  labels:
    app: user-center
    type: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      type: backend
      app: user-center
  template:
    metadata:
      name: user-center
      labels:
        app: user-center
        type: backend
    spec:
      containers:
        - name: user-center
          image: us.gcr.io/gcloud-test-429808/user-center:latest
          ports:
            - containerPort: 8084