#MySQL Docker Compose
version: '3'
services:
  course-mysql-db:
    image: mysql
    container_name: course-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: course_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3306:3306"
    volumes:
      - ../data/mysql:/var/lib/course-mysql-db
    restart: unless-stopped