apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
    type: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      type: backend
      app: api-gateway
  template:
    metadata:
      name: api-gateway
      labels:
        app: api-gateway
        type: backend
    spec:
      containers:
        - name: api-gateway
          image: us.gcr.io/gcloud-test-429808/api-gateway:latest
          ports:
            - containerPort: 8765