spring:
  data:
    mongodb:
      database: payment_db
      host: localhost
      password: user123
      username: user
      uri: mongodb://user:user123@localhost:27017/payment_db?authSource=admin
  cloud:
    compatibility-verifier:
      enabled: false
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

eureka:
  instance:
    hostname: ${spring.application.name}
    metadata-map:
      management.context-path: ${server.servlet.context-path}/actuator
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://35.185.34.88:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
      enabled: true

logging:
  file:
    name: ./../data/logs/${spring.application.name}.log
  level:
    org.springframework: DEBUG


openapi:
  service:
    title: Payment Center
    version: 1.0.0
    url: ${server.servlet.context-path}
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

cors:
  allowedOrigin: '*'
  allowedMethods: '*'
  allowedHeaders: '*'
  allowedCredentials: 'false'
  corsConfiguration: '/**'