#PostgreSql Docker Compose
version: '3'
services:
  user-postgresql-db:
    image: postgres
    container_name: user-postgresql-db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user123
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/user-postgresql-db
    restart: unless-stopped