apiVersion: v1
kind: Service
metadata:
  name: actuator-admin-server
spec:
  type: LoadBalancer
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: actuator-admin-server
    type: backend