spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: avnadmin
    password: AVNS_2ygEdQRw_tTEN6Ysj_5
    url: jdbc:mysql://microservce-db-ft-ff4b.h.aivencloud.com:20569/defaultdb?user=avnadmin
    name: defaultdb
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 49154
      database: 0
      timeout: 1000
      url: redis://default:redispw@localhost:49154
      password: redispw

eureka:
  instance:
    hostname: ${spring.application.name}
    metadata-map:
      management.context-path: ${server.servlet.context-path}/actuator
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  file:
    name: ${spring.application.name}.log